const mongoose = require("mongoose");

const jobOfferSchema = new mongoose.Schema(
  {
    publicationDate: {
      type: Date,
      required: true,
    },
    expirationDate: {
      type: Date,
      required: true,
    },
    jobTitle: {
      type: String,
      required: true,
    },
    department: {
      type: String,
      required: true,
    },

    typeOfOffer: {
      type: String,
      enum: ["Stage", "Intérim", "Freelance", "Emploi", "Consultant"],
      default: "emploi",
    },

    educationLevel: {
      type: String,
      enum: [
        "Aucune",
        "BAC+7 et plus",
        "BAC+6",
        "BAC+5",
        "BAC+4",
        "BAC+3",
        "BAC+2",
        "BAC+1",
        "BAC",
        "BT",
        "Terminale",
      ],
      required: true,
    },

    fieldOfStudy: {
      type: String,
      enum: [
        "Aide soignant",
        "Architecture",
        "Archivage",
        "Assistanat de Direction",
        "Assurance",
        "Auxiliaire en pharmacie",
        "Bâtiment",
        "Biochimie",
        "Biologie",
        "Biomédical",
        "Blanchisserie",
        "Boucherie",
        "Caisse",
        "Cariste",
        "Carrelage",
        "Chaudronnerie",
        "Chimie",
        "Commerce et Administration des Entreprises",
        "Commerce/Ventes",
        "Communication",
        "Contrôle de gestion/Audit",
        "Couture/Broderie",
        "Délégation médicale",
        "Documentation",
        "Economie",
        "Education/Enseignement",
        "Electrobiomédical",
        "Electromécanique",
        "Electronique",
        "Energétique",
        "Entretien/Nettoyage",
        "Ferraillage",
        "Ferronnerie",
        "Finances/Comptabilité",
        "Fiscalité",
        "Généraliste",
        "Génie Civil/Travaux publics",
        "Gestion des PME-PMI",
        "Hôtellerie/Restauration",
        "Hydraulique",
        "Incendie Prévention",
        "Infographie",
        "Informatique",
        "Informatique de Gestion",
        "Juridique/Droit",
        "Logistique/Transport",
        "Magasinage",
        "Maintenance des Systèmes de Production",
        "Maintenance Informatique",
        "Maintenance véhicules et engins",
        "Management",
        "Marketing",
        "Mécanique",
        "Médecine/Santé",
        "Menuiserie",
        "Musique",
        "NTIC",
        "Optique/Lunetterie",
        "Peinture",
        "Pharmacie",
        "Phytosanitaire",
        "Plomberie",
        "Psychologie",
        "Qualité",
        "Ressources Humaines",
        "Sciences sociales",
        "Secrétariat",
        "Sécurité/Défense",
        "Sociologie",
        "Soudure",
        "Sports",
        "Statistiques",
        "Tapisserie",
        "Télécommunications",
        "Traduction/Interprétariat",
        "Transit/Transport",
        "Transport (Chauffeur)",
        "Urbanisme",
        "Vitrerie",
      ],
      required: true,
    },

    experienceLevel: {
      type: String,
      enum: ["Aucune", "1 an", "2 ans", "3 ans", "4 ans", "5 ans", "+6 ans"],
      required: true,
    },

    jobDescription: {
      type: String,
      required: true,
    },
    jobProfile: {
      type: String,
      required: true,
    },

    requiredDocuments: {
      type: String,
      enum: ["CV", "CNI", "Lettre de motivation"],
      required: true,
    },
  },
  {
    timestamps: true,
  }
);

module.exports = mongoose.model("JobOffer", jobOfferSchema);
